### ISSUE TITLE
How to activate the Plugin

### ISSUE THREAD

**Issue by dkfz2018** [bpedersen2/indico-cron-advanced-cleaner#1]
Hi,

how can i active the plugin ?

PLUGINS = {'AdvancedCleanerCronjobsPlugin'}

in the /opt/indico/etc/indico.conf 

Gives me a error when accessing the website again.

**Comment by bpedersen2** [comment]
Hi,
The plugin name for indico is:       
    'cron_advanced_cleaner',

**Comment by bpedersen2** [comment]
You can always use 

  indico setup list_plugins
to list the correct activation names ( they are coming from the entrypoints definition in setup.py)
