### ISSUE TITLE
Question: Hash usage

### ISSUE THREAD

**Issue by amandahla** [bpedersen2/indico-cron-advanced-cleaner#2]
Hi,

Is there a specific reason to replace ['first_name', 'last_name', 'phone', 'address',] fields for a hash instead of an empty or fixed value like "REMOVED"?

**Comment by bpedersen2** [comment]
Yes, we still wanted distinct values, but technically empty or -removed- would probably work.

**Comment by amandahla** [comment]
Thanks!
